### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by yxydw98** [vinnnyr/epsilon-star-coverage-path-planner#1]
Hi, I am building the package with Ubuntu 20.04 and ros foxy and I encountered this issue. 

colcon build --packages-up-to explored_space_costmap_plugin
Starting >>> explored_space_costmap_plugin
--- stderr: explored_space_costmap_plugin                             
/home/yxydw98/CPP/src/epsilon-star-coverage-path-planner/explored_space_costmap_plugin/src/explored_space_layer.cpp: In member function ‘virtual void explored_space_costmap_plugin::ExploredSpaceLayer::onInitialize()’:
/home/yxydw98/CPP/src/epsilon-star-coverage-path-planner/explored_space_costmap_plugin/src/explored_space_layer.cpp:34:21: error: ‘using SharedPtr = class std::shared_ptr<rclcpp_lifecycle::LifecycleNode>’ {aka ‘class std::shared_ptr<rclcpp_lifecycle::LifecycleNode>’} has no member named ‘lock’
   34 |   auto node = node_.lock();

May I know what is the reason? Is it because a wrong type was assigned to the node variable that does not have the .lock() method? Thank you for you time.

**Comment by yxydw98** [comment]
I tried building under ros-galactic and it works. I think the reason may due to some of the changes in the navigation2 packages.

**Comment by vinnnyr** [comment]
thanks for trying out the repo @yxydw123456 . I am sure you noticed this by now, but this repo is kind of abandoned / not being actively worked on. I had high hopes -- but just not enough time. 

You are right -- I probably had developed this against `galactic` nav2 and not `humble`.  

if you end up getting this algorithm to work, let me know! 

Closing issue for now.
